### ISSUE TITLE
Output used Args

### ISSUE THREAD

**Issue by confile** [Putnami/putnami-gradle-plugin#10]
It would be great if you could output the complete command with args in the log to see if the configuration was done correctly. 

I did: 
```
putnami {
  module 'test.gwt-module'
  
  gwtVersion = "2.7.0"
  dev {
    bindAddress = "192.168.178.26"
    jsInteropMode = "JS"
    logLevel = "INFO"
  }
  
}
```

But I have no idea if the jsInteropMode or logLevel configuration was set correctly.

**Comment by fdumay** [comment]
You can already see the java command with `gradle gwtDev --info`.
Otherwise I agree that more log must be added.

**Comment by confile** [comment]
Are my options set correctly? Especially jsInterop and logLevel?

**Comment by fdumay** [comment]
Yes it is. in case of a wrong value (on enum) gradle fails.

i.e. `No enum constant fr.putnami.gwt.gradle.extension.LogLevel.sfdds` 

Do you meet an error?

**Comment by confile** [comment]
No it works. What about the ``-strict``argument?

**Comment by fdumay** [comment]
As it works, I close that issue.
We're gonna open a new issues later : 
* Add parameter assertions
* Add finer logs
