### ISSUE TITLE
transitive project dependencies are not resolved correctly

### ISSUE THREAD

**Issue by confile** [Putnami/putnami-gradle-plugin#13]
I have two projects in a flat stricture 

```
/
/test-core
/test-gwt
```

test-core uses a lib called dagger in its ``build.gradle`` like this:

```
dependencies {
  apt name: 'dagger-compiler-2.0-20150122.022637-13-jar-with-dependencies'

  compile 'com.google.guava:guava:14.0.1'
  compile 'javax.inject:javax.inject:1'
  compile 'com.google.dagger:dagger:2.0-SNAPSHOT'
  
  compile name: 'dagger-2.0-SNAPSHOT-sources'
  compile name: 'javax.inject-1-sources'
 } 

repositories {
  flatDir {
    dirs 'lib'
  }
}
```

The main project ``test-gwt`` is using ``test-core``. settings.gradle of test-gwt is: 
```
includeFlat "test-gwt"
project(":test-gwt").name = "test-gwt"
```
The build.gradle file of test-gwt is: 
```
dependencies {  
  compile(project(':test-core')) {
    transitive = false
  }
}

putnami {
  module 'test.mobile.mobilePhoneGapIOS'
}
```

When I compile (``gradle build`` on test-gwt) I get the error:
```
:compileJava/Users/test/Documents/Grails/GGTS3.6.3-SR1/test-core/build/libs/test-core-1.0.jar(test/core/shared/helper/test2/MyWidgetGinjector.class): warning: Cannot find annotation method 'modules()' in type 'Component': class file for dagger.Component not found
```

This is strange because the dependencies should not be resolved. Do you know how to solve it? It works perfect in the old GWT gradle plugin.

**Comment by fdumay** [comment]
If you exclude transitive dependencies (at least the sources of those deps) on the webapp project, GWT will not be able to  compile the project.
I don't know why it's working on the old gwt-gralde-plugin, but I guess that steffen made a dirty trick.

**Comment by fdumay** [comment]
@confile do you agree?  the GWT cannot compile the project is you exclude the transitive libs!

**Comment by confile** [comment]
This issue is fixed. I use: 

```
compile(project(':test-core'))
```
