### ISSUE TITLE
Eclipse does not show errors in Project Explorer

### ISSUE THREAD

**Issue by confile** [Putnami/putnami-gradle-plugin#19]
I am not sure if this belongs to your gradle plugin. When I use two linked projects in eclipse it does not show the error sign in the project explorer when there are errors. I am used to this in a normal GWT or Java project. Is there any way how I can configure this?

**Comment by fdumay** [comment]
I don't see any reasons why the errors are not collected on eclipse. 
Which eclipse plugins do you use? 
Did you import your projects use the gradle plugin or via `gradle eclipse`?

**Comment by confile** [comment]
I use the gradle plugin from the eclipse marketplace:

![eclipse_marketplace](https://cloud.githubusercontent.com/assets/64265/6373958/269197ea-bd0e-11e4-8940-13d28e9013f2.png)

To create a new project I use: Eclipse > New > Gradle Project.

**Comment by fdumay** [comment]
Can you try to update the gradle project configurations : 
Right click on the project>Gradle>Refresh All?

By the way the #13 is still an issue?

**Comment by confile** [comment]
I closed issue #13

**Comment by confile** [comment]
Great thank you!
