### ISSUE TITLE
Feature request: Integration with GWT Eclipse Plugin

### ISSUE THREAD

**Issue by confile** [Putnami/putnami-gradle-plugin#21]
When creating a GWT application with the GWT eclipse plugin you have some nice features like the following. Code Completion works fine in JSNI code block when you do something like this:

```
callback.@org.test.pgplugins.client.actionSheet.ActionSheetCallback::onButtonTap(I)(buttonIndex);
```

When you create a gradle project in eclipse and use the putnami GWT plugin you do not have this feature.

Do you see any possibility to integrate it? It makes coding way more simple.

**Comment by branflake2267** [comment]
Just a note, when I saw this, GPE should be coming out with patch soon, its near its next phase in development too. I've got a code launcher that will go in soon too for it, which will also work with WTP servers.

**Comment by confile** [comment]
@branflake2267 What is GPE? And when is soon? :-)

**Comment by fdumay** [comment]
The eclipse integration is planned for the v0.3. The goal is to properly setup both GPE and WTP when the project will be import.

For note : GPE is the google eclipse plugin which is reponsible of the GWT and GAE integration in eclipse.

@branflake2267 do you know if the GWT part of the GPE will be release to the GWT community?

**Comment by branflake2267** [comment]
I'm not sure yet, there are a few more hoops to jump through.
