### ISSUE TITLE
When I run gwtDev more than once I get a AdressAlreadyInUse: Bind exception

### ISSUE THREAD

**Issue by jgleoj23** [Putnami/putnami-gradle-plugin#22]
I think this means that the address isn't being stopped right. I tried using the eclipse stop button and the gwtStop task several times and still got the error. How can I completely shut down the server so that I don't get this error?

**Comment by confile** [comment]
On OSX use your command line tool: 

```
killall -9 java
```

This should kill all your java processes.

**Comment by jgleoj23** [comment]
Thanks. I currently just quit my IDE but this should be faster. It's still inconvenient because it'd shut down all my other java programs too. I see all of the java processes when I look in activity monitor but I can't tell which ones are for gwtDev and which are for other java programs. If I could just tell which ones are for gwtDev then I could just shut down those rather than shutting down every java program

**Comment by fdumay** [comment]
If you need to run gwtDev on 2 projects you may change the port of jetty and code server on at least one of them.
Can you explain a bit more your use case? I need to understand what's going wrong, or why the CodeServer didn't stop on gradle shutdown.

```
dev{
   port = 9875
}
jetty{
   port = 8081
}
```

**Comment by jgleoj23** [comment]
I tried your suggestion of changing the ports and it didn't work. I'm not running several projects. I have 1 simple project. From intellij I run gwtDev and then once it says the server started and the code server is ready I run gwtStop. Then once gwtStop and gwtDev both say build success I close both windows. Then I run gwtDev again. I don't understand why this is happening but I can just quit all of my java processes.

**Comment by fdumay** [comment]
Well, the gwtStop task stops the jetty server but doesn't stop the CodeServer. I need to find a way to stop the CodeServer remotely.
By now, if you stop the gradle task (cmd key + c), the jetty and CodeServer should stop normaly. 
Note : I do not use IntellyJ, so I don't know how to kill the gradle task.

**Comment by jgleoj23** [comment]
Ok thanks. I'll just keep stopping the process.
