### ISSUE TITLE
gwt-dev should not be added as a dependency in the generated pom

### ISSUE THREAD

**Issue by hightea** [Putnami/putnami-gradle-plugin#24]
When you use `gradle install` (on the pwt core project for an example), the generated pom should not contains the com.google.gwt:gwt-dev dependency.

Actually gwt-dev.jar should not be present in the generated war too.

**Comment by mwyszomierski** [comment]
@hightea did you manage to resolve this? I'm getting gwt-dev.jar and gwt-user.jar in the generated war as well.
