### ISSUE TITLE
GwtSetUpTask does not respect sourceSets configuration

### ISSUE THREAD

**Issue by vhkrausser** [Putnami/putnami-gradle-plugin#26]
If your project structure is not in the common maven format, the plugin stops working because GwtSetUpTask spects to find sources on src/main/java  and web sources on src/main/webapp.

**Comment by fdumay** [comment]
It's right! But the GwtSetUpTask is not avaliable yet. 
Actually as draft, the goal of this task is to emulate the maven archetype plugin.   
Anyway need to fix it. Thank you for the review.

**Comment by fdumay** [comment]
The setup feature will be drop, so I close this issue
