### ISSUE TITLE
main only folder as possibility for source ?

### ISSUE THREAD

**Issue by klaun76** [Putnami/putnami-gradle-plugin#28]
Hi

I'm newbie to contribute on github, so excuse me if i posted on wrong place my request. I participate on gwt-gradle project with multiple programs in one repository. When source is located in src/main putnami plugin works well for deploy and gwtDev. But when its located in other folder, we cannot deploy. Compiler report. [ERROR] Unable to find 'path/<ProjectName>.gwt.xml' on your classpath; could be a typo, or maybe you forgot to include a classpath entry for source?

I'm not leader programmer, just junior, but im person who has to rename source files before deploying and then put them together. And also this problem does not allow us to create some reasonable autobuild.

I've been googling around but i did not find any solution. Could you please write me some hits? In fact i would appreciate any help.

thanks
.mrtn

**Comment by fdumay** [comment]
Hi,

You're on the right place ;)
Can you please tell me a bit more? Why do you need to declare other sources folders? and how do you declare those folder in your build.gradle?
I don't know your context but in case you have many libraries or modules, it would be preferable to create many sub project rather than other source folders.

**Comment by klaun76** [comment]
hi

glad to hear that im on right place.
as always, i'm in (team is) a rush as every programmer theese days. problem is that were developing our sdk along with several programs/games which should run on sdk. Project is pretty complex with several external and internal repositories. So at start we decided to have multiple games in one repository for quicker implementation of sdk changes. Which led to have several src/<gamename> source files. For every game we have own build.gradle file which depends on i do not know how many other gradle settings or build files. 

Our main programmer has other more pressing issues, and we are stucked at renaming source files before every deploy.

Im not sure if this issue can be solved. If you think that with more informations problem can be solved, i will consult @ work for better informations.

cheers
.mrtn

**Comment by klaun76** [comment]
we found some other solution
