### ISSUE TITLE
Flag  -generateJsInteropExports is missing

### ISSUE THREAD

**Issue by confile** [Putnami/putnami-gradle-plugin#29]
Is GWT 2.8 you get the following warning: 

> The experimental -XjsInteropMode option is deprecated and will be removed very soon. See https://goo.gl/uMdOQS for migration instructions.

The JS Interop document says: 

> Remove -XjsInteropMode JS flag and add -generateJsInteropExports flag.

How can I use the ``-generateJsInteropExports`` flag?

**Comment by confile** [comment]
@fdumay could you please add a way to insert generic tags?

**Comment by confile** [comment]
See: https://github.com/Putnami/putnami-gradle-plugin/commit/2a316987278b43345d506d38ce4a585353348fb1

**Comment by fdumay** [comment]
Hi,
@confile I add an extraArgs option on devOption and compileOption. Making possible to add any arg to the compiler.
For the exception, I forgot to add the -generateJsInteropExport to the devOption. It's now fixed.

**Comment by confile** [comment]
great thank you.
