### ISSUE TITLE
improving and fixing the documentation and I get an error when I use your plugin on a former maven project

### ISSUE THREAD

**Issue by jgleoj23** [Putnami/putnami-gradle-plugin#3]
There's a minor typo at https://github.com/Putnami/putnami-gradle-plugin/blob/master/README.md It mispells build.gradle as "build.gralde". Also, it'd be nice if there was some documentation on integrating with eclipse. 
I made a brand new project and successfully set it up with gradle, gwt, eclipse, and your plugin but I'm trying to convert a GWT maven project to a gradle project. I used the gradle init plugin and built the project and I got a build success. Unfortunately, I got a build failure once I added your plugin. I got this error.
[ERROR] Unexpected internal compiler error
java.lang.IncompatibleClassChangeError: class com.google.gwt.dev.javac.asm.CollectMethodData has interface org.objectweb.asm.MethodVisitor as super class. I googled the error and found out that gwt needs asm 5 when I have asm 3.  I checked my gradle dependencies and saw both asm 3 and asm 5. I think that is the cause of my error. I didn't purposely get asm 3 in my build.gradle so I think asm 3 is a transitive dependency. I added the following to my build.gradle in an attempt to get an error message about whatever is getting asm 3:

configurations.all {
	resolutionStrategy {
    // fail eagerly on version conflict (includes transitive dependencies)
    // e.g. multiple different versions of the same dependency (group and name are equal)
    failOnVersionConflict()
	}
}
This gave me the following error message:
:compileJava

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all dependencies for configuration ':compile'.
> A conflict was found between the following modules:
   - com.google.gwt:gwt-user:2.7.0
   - com.google.gwt:gwt-user:2.4.0
I looked at my build path and I couldn't see gwt-user:2.4.0 or anything of the sort. I have no idea how I got gwt 2.4.0.  or how I can get rid of it.

**Comment by fdumay** [comment]
Hi,

Thank you for those quick feedbacks. 
I'am quite happy that you found only one typo ;), but I'am pretty sure that many others will be raised later.

I didn't take care about the eclipse integration yet. For my part I only use a Gradle Plugin and it works fine. It can be some classpath issues with the Google Plugin for Eclipse but I didn't tried yet. Anyway you're right it need a bit of documentation.

Concerning you real issue:
To use this plugin you will have to upgrade to GWT 2.7.
Globally you don't need add GWT deps, in case that GWT 2.4 libs are transitives, you can exclude it and try to rebuild your project.
I will not be able to help you much more with those few inputs. If you provide the `build.gradle` or the output of `gradle dependencies` I'll maybe be able to go further (of course can be anonymized or sent as PM) . 

Regards,

-- Fabien

**Comment by jgleoj23** [comment]
thanks for responding so quickly. I was experimenting with a brand new project and saw the gwt-servlet2.4 jar in the class path when I added mvp4g as a dependency. That's probably the transitive dependency so I'll try removing mvp4g. It still seems wierd that I didn't see the gwt-servlet2.4 jar before.

**Comment by fdumay** [comment]
In normal case on maven (or gradle) only keeps one artifact for the tuple groupId:artifactId, so if you've declared gwt-servlet in your project the one from mvp4g is skiped. In our case the gwt-servlet is not automaticly added so...

**Note :** You can add this artifact with:

```
putnami{
    gwtServletLib = true;
}
```

**Comment by jgleoj23** [comment]
I tried adding the gwtServletLib = true; and removing mvp4g. It didn't work. I got that other project to work in eclipse so I think I should work on the brand new gradle project I made. I'll gradually add the stuff from my current project to it. If I get the same error I'll know the cause is whatever I just added. If I don't get the same error then that's even better.

**Comment by jgleoj23** [comment]
I got it working! I went on the command line did the following:
cd myProjectDirectory
gradle dependencies
This showed me my whole tree of dependencies so I saw who was getting asm 3.
google gin was getting asm 3. Unfortunately, that means that this will be a common problem since most people either use gin themselves or use a library that uses gin. I manually excluded asm 3 by following instruction at https://gradle.org/docs/current/userguide/dependency_management.html. In my case I didn't get gin directly. Instead I got it from mvp4g. I went in my build.gradle and changed it to this:
dependencies {
       ...
      	compile ('com.googlecode.mvp4g:mvp4g:1.5.0') {
		 exclude module: 'asm'
	}
       ...
}
Once I rebuilt it worked. 

       Since this will probably be a common error unless I recommend warning users until you find a more elegant solution. 

      I also think you should add to the documentation that the build init plugin although unreliable is at least useful for converting many maven dependencies to gradle dependencies. I'm no expert on gradle but I can tell you exactly how I integrated the project with eclipse or create actual documentation of what I did if you want. Thanks for the plugin.

**Comment by fdumay** [comment]
Okay, great. I'm glad that you get it working.

I'am not sure, how much this use case is common. I mean the classpath of mvp4g and gin doesn't seem to be compliant with GWT 2.7. Anyway I'll refresh the documentation in order to warn about that the dependencies must be accorded to GWT 2.7.
If you have documented the eclipse integration, I'll be happy to integrate it on the readme.

Do not thank me for this plugin, as First contributor you are more than very welcome.

**Comment by jgleoj23** [comment]
ok. I already figured out how to contribute to the README and I'll do the documentation.
