### ISSUE TITLE
Add Debugging Task for SuperDevMode

### ISSUE THREAD

**Issue by confile** [Putnami/putnami-gradle-plugin#30]
There is an Eclipse plugin: http://sdbg.github.io/ which enables debugging in SuperDevMode.

Do you see a way of having a task for that?

**Comment by fdumay** [comment]
I tried for the first time to use the SDBG plugin. And it seems to work pretty well. :D

To use it you have to:
1. run the task gwtDev
2. in the eclipse debug configuration add a launch chrome.
3. set the url (I.E. http://localhost:8080/)
4. set the project where the sources are.
5. Run the configuration
6. Add some breakpoints.

And enjoy.

Well actually, the debbuging is not as powerfull as the the java one, but it makes the job easier than under chrome.

**Comment by confile** [comment]
@fdumay I think you have to use 

1. run task gwtCodeServer (to get Superdevmode)

**Comment by fdumay** [comment]
@confile, ``gwtCodeSever`` can also be an option. 
I mean ``gwtDev`` runs both code SuperDevMode and jetty.
Did you get it work with ``gwtCodeServer``?

**Comment by confile** [comment]
Yes I get it work. You should change the description of the task ``gwtDev`` saying that it runs Super Dev Mode.

**Comment by confile** [comment]
@fdumay what do you think about my last comment?

**Comment by confile** [comment]
See: https://github.com/Putnami/putnami-gradle-plugin/pull/32

**Comment by fdumay** [comment]
I agree, all the tasks description can be completed.
PR was accepted.
