### ISSUE TITLE
debugPort Option meaning?

### ISSUE THREAD

**Issue by confile** [Putnami/putnami-gradle-plugin#31]
What is the ``debugPort`` option used for?

**Comment by fdumay** [comment]
The ``debug*``options placed on the jetty are used to debug the server side.

You can debug the jetty side with:
 
```
putnami{
    jetty {
        debugJava = true
        debugPort = 8000
        debugSuspend = false
    }
}
```

Note that you may also increase the Xmx.

**Comment by confile** [comment]
I see. Could you add this to the docs.

**Comment by fdumay** [comment]
Done.
@confile, feel free to submit pull request, every piece of help is welcome :) .

**Comment by fdumay** [comment]
@confile, Is this issue is closed for you?

**Comment by confile** [comment]
yes thanks
