### ISSUE TITLE
Issues when  this plug-in with Gardle 2.13 and GWT 2.8-SNAPSHOT:

### ISSUE THREAD

**Issue by hrstoyanov** [Putnami/putnami-gradle-plugin#36]
Hi,
I found 4 issues with this plug-in in Gardle 2.13 and GWT 2.8-SNAPSHOT:
0 where is the **-gen** compiler option?

1 Where is the **enableClosureCompiler** flag in **compile {...}** section?

2 I experience the same issue as described [here](https://github.com/steffenschaefer/gwt-gradle-plugin/issues/102):
if I put this in my project's property file: 
**=====gradle.properties========**
```
gwt_compiler_optimize =0
gwt_compiler_draftCompile = false
```
And try to refernce these properties in my build:
**======gradle.build==========**
```
putnami{
  compile {      
        draftCompile = gwt_compiler_draftCompile       
        optimize = gwt_compiler_optimize
  }
}
```
when I compile with: **./gradlew -i gwtCompile**  , I see strange command line parameters for the gwt compiler in the output, like:
```... -draftCompile -optimize 48 ...```
But I expected only: ``` ...-optimize 0 ...``` ?
It seems as if string properties come through ok, but boolean and integer - not. Do you know what is going on?

3 I keep getting this error:
```
Loading inherited module 'com.xxxxx.web.App'
   Loading inherited module 'org.jboss.errai.enterprise.Jaxrs'
      Loading inherited module 'com.google.common.collect.Collect'
         [ERROR] Unable to find 'com/google/common/collect/Collect.gwt.xml' on your classpath; could be a typo, or maybe you forgot to include a classpath entry for source?
```
This seems to be related to a missing Guava library of some sort in GWT 2.8 ? Any idea?

Thanks.

**Comment by hrstoyanov** [comment]
Here is a temporary workaround for 2 that works:

```
    compile {
        ...
        optimize = gwt_compiler_optimize.toInteger();        
        draftCompile = gwt_compiler_draftCompile.toBoolean();
    }
```
As I mentioned, you only need the fix for boolean and integer params.

**Comment by fdumay** [comment]
Thank you for the feedbacks.
Can please open one issue by topic. it will be simpler to comment and fix.

**Comment by fdumay** [comment]
1. the enableClosureCompiler is available but not documented. All the experimental compiler features are not documented. have a look at https://github.com/Putnami/putnami-gradle-plugin/blob/master/src/main/java/fr/putnami/gwt/gradle/extension/CompilerOption.java

**Comment by fdumay** [comment]
For the point 4: what is the scope of your guava dependency? because related to the #37 the compileOnly is not implemented yet in this plugin

**Comment by hrstoyanov** [comment]
@fdumay Thanks for looking into 4. It turns out this is a direct effect of this plug-in not understanding **compileOnly**, issue #37. Switching to **providedCompile** fixed the issue:
```
providedCompile "com.google.guava:guava-gwt:${guava_version}"
```

**Comment by hrstoyanov** [comment]
@fdumay Thanks for looking into 2. I should have broken down my feedback into several issues, sorry.
I see that you already changed the code to accept string properties. Do you still want me to open a separate issue for 2 ? If not, let me test the fix tonight and open an issue only if further work is needed.

**Comment by fdumay** [comment]
@hrstoyanov you don't need to open more issues. but next time try to split the issues.

**Comment by hrstoyanov** [comment]
@fdumay Regarding issue 0, I am not sure it is an issue at this point. I filed a separate issue #38 for item 1. It looks like you took care of item 2 and item 3 is filed as separate issue #37 

You may want to close this issue #36 then?

**Comment by hrstoyanov** [comment]
This issue was replaced by other ones
