### ISSUE TITLE
[Gradle 2.13] compileOnly dependencies?

### ISSUE THREAD

**Issue by hrstoyanov** [Putnami/putnami-gradle-plugin#37]
Recently Gradle introduce the [compileOnly dependencies](http://gradle.org/blog/compile-only-dependencies/) for normal java project, which act like **providedCompile** for war projects. While this plug-in seems to understand **providedCompile**, it skips **compileOnly** dependencies.

**Comment by fdumay** [comment]
Can be nice to have both compileOnly and providedCompile

**Comment by hrstoyanov** [comment]
@fdumay better fix that one as using **compileOnly** silently drops the dependency leading to compile errors. Then GWT library projects will enjoy the same benefits as WAR projects with **providedCompile**, which leads to smaller wars ultimately.

**Comment by fdumay** [comment]
Right, comileOnly will be more gradle compliant! 
Will use compileOnly in the release 0.5.0, as it will break the compatibility with gradle < 2.12 I need to do several tests.

**Comment by gkresic** [comment]
This issue seems to be fixed in 0.6.1 and I suppose it can be closed now.

**Comment by fdumay** [comment]
That is right. I close it.
