### ISSUE TITLE
Please, register this plug-in with Gradle plugins portal

### ISSUE THREAD

**Issue by hrstoyanov** [Putnami/putnami-gradle-plugin#39]
Are there any plans to register this plug-in with the Gradle plugin portal? This would lead to even more compact usage code, for example:
 
```
plugins {
    id "fr.putnami.gwt:putnami-gradle-plugin" version "0.3.0"
}
```

See:
https://plugins.gradle.org/docs/submit
http://gradle.org/blog/new-gradle-plugin-portal/

**Comment by fdumay** [comment]
published on the gradle repository

https://plugins.gradle.org/plugin/fr.putnami.gwt

this syntax works
``` 
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "gradle.plugin.fr.putnami.gwt:putnami-gradle-plugin:0.3.0-SNAPSHOT"
  }
}
```
apply plugin: "fr.putnami.gwt"
but this one doesn't -
```
plugins {
    id "fr.putnami.gwt" version "0.3.0-SNAPSHOT"
}
```
I need to continue on this task

**Comment by fdumay** [comment]
@hrstoyanov since I released the 0.3.0, it seems to be ok. I let you try and close the issue if ok.

**Comment by hrstoyanov** [comment]
@fdumay 
Looks great and I see you already updated the docs!
One lat suggestion: I recommend you mention in the docs that the "old way" still works - see how the folks behind the [jcenter plugin](https://github.com/bintray/gradle-bintray-plugin) document theirs - you may directly borrow the same text (see below) and paste it into your documentation, just change the plugin reference:

=========================
Apply the plugin to your Gradle build script

To apply the plugin, please add one of the following snippets to your **build.gradle** file:

**Gradle >= 2.1**

plugins {
    id "com.jfrog.bintray" version "1.6"
}
Currently the "plugins" notation cannot be used for applying the plugin for sub projects, when used from the root build script.

**Gradle < 2.1**

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.6'
    }
}
apply plugin: 'com.jfrog.bintray'
If you have a multi project build make sure to apply the plugin and the plugin configuration to every project which its artifacts you wish to publish to bintray.
======================================

**Comment by hrstoyanov** [comment]
@fdumay I modified the documentation a bit, would you like to insert the following snippet (and please close this issue either way):


...To apply the plugin, please add one of the following snippets to your **build.gradle** file:

**Gradle >= 2.1**

```groovy
plugins {
    id "fr.putnami.gwt" version "0.3.0"
}
```

Currently the "plugins" notation cannot be used for applying the plugin for sub projects, when used from the root build script.

**Gradle < 2.1**

```groovy
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'fr.putnami.gwt:putnamigradleplugin:0.3.0'
    }
}
apply plugin: 'fr.putnami.gwt'
```

If you have a multi project build make sure to apply the plugin and the plugin configuration to every project.

**Comment by fdumay** [comment]
done!
If you have more suggestions, can you please push a pull request. it will be simpler :)
