### ISSUE TITLE
Version 0.3.0 not published on maven centra?

### ISSUE THREAD

**Issue by hrstoyanov** [Putnami/putnami-gradle-plugin#40]
You will only see up to version 0.2.0

**Comment by fdumay** [comment]
Oh thank you, I did but, it was in a staging repository :)
I've commited it, It should be available soon.

**Comment by hrstoyanov** [comment]
Thanks, still waiting to see it at Maven Central, I know it could take some time. Once there I/you can test and close this issue #40, hopefully.

**Comment by hrstoyanov** [comment]
Ok it's been 24hrs already and 0.3.0 is not on maven central?

**Comment by fdumay** [comment]
I don't know why it didn't work at at the first time :/
FIxed : http://search.maven.org/#search%7Cga%7C1%7Cputnami-gradle-plugin

**Comment by danielvaughan** [comment]
The documentation says: 

{code}
classpath 'fr.putnami.gwt:putnamigradleplugin:0.3.0'
{code}

This should be:

{code}
classpath 'fr.putnami.gwt:putnami-gradle-plugin:0.3.0'
{code}
