### ISSUE TITLE
-XenableClosudeCompiler to be removed from GWT 2.8

### ISSUE THREAD

**Issue by hrstoyanov** [Putnami/putnami-gradle-plugin#42]
https://gwt-review.googlesource.com/#/c/15110/

According to the above, this option is going away. Should this option  be removed from this plugin as well? 

I started discussion here as well:
https://groups.google.com/forum/#!topic/google-web-toolkit/Qgd2C6CgFzY

**Comment by fdumay** [comment]
Hi, if we remove this option, it will break the compatibility for the user that use a gwt < 2.8
We maybe just add a warning to display that this option is not support any more.

**Comment by hrstoyanov** [comment]
@fdumay 
The best way to handle this seems to be:
1. Do not remove the option, so no one's builds get broken.
2. Make the option do nothing. Closure compiler never worked in 2.7 or 2.8 anyway, according to the forum dicussion
3. Do print a warning when the option is used.
4. If this is a documented option, remove the docs.

**Comment by fdumay** [comment]
Well, Since the closure compiler never properly worked, lets remove this option!

**Comment by hrstoyanov** [comment]
Your call!
