### ISSUE TITLE
Disable Jetty downloads?

### ISSUE THREAD

**Issue by hrstoyanov** [Putnami/putnami-gradle-plugin#44]
This plugins downloads Jetty jars on its own, ignoring the Gradle local cache. Is there a way to force it to look for the Jetty jars in the Gradle cache instead, and not to try to download jetty jars directly?

**Comment by hrstoyanov** [comment]
See alos: 
https://groups.google.com/forum/#!topic/google-web-toolkit/KtdRAWNotXE

Is there any way to manipulate the included jars during compilation. Right now, I think they are added and the developer can not use the Gradle exclusion capabilities to remove unnecessary jars.

**Comment by fdumay** [comment]
The plugin does not download Jetty on its own, it use the Gradle cache. but use a pre-defined version 9.2.7.
This version can be changed with `putnami{ jettyVersion = "9.3.9.v20160517"}`

Once downloaded for the first time, Jetty is in cache in gradle then not downloaded any more.

```

jettyConf
\--- org.eclipse.jetty:jetty-runner:9.2.7.v20150116
     +--- org.eclipse.jetty:jetty-plus:9.2.7.v20150116
     |    +--- org.eclipse.jetty:jetty-webapp:9.2.7.v20150116
     |    |    +--- org.eclipse.jetty:jetty-xml:9.2.7.v20150116
...
```

**Comment by hrstoyanov** [comment]
Ok, I will play with this again and see if I can replicate the issue at all. Thanks.

**Comment by fdumay** [comment]
Is it still an issue?

**Comment by hrstoyanov** [comment]
I will close this one

**Comment by hrstoyanov** [comment]
@fdumay 
See the comments from Thomas:
https://groups.google.com/forum/#!topic/google-web-toolkit/KtdRAWNotXE
