### ISSUE TITLE
Redundant re-compilation?

### ISSUE THREAD

**Issue by hrstoyanov** [Putnami/putnami-gradle-plugin#45]
I see something in my Gradle logs that makes me think this plug-in fails to detect when a GWT re-compile is necessary. Here is the log:
```
Skipping task ':myapp-war:compileJava' as it is up-to-date (took 0.084 secs).
:myapp-war:compileJava UP-TO-DATE
:myapp-war:compileJava (Thread[Daemon worker Thread 4,5,main]) completed. Took 0.094 secs.
:myapp-war:processResources (Thread[Daemon worker Thread 4,5,main]) started.
:myapp-war:processResources
file or directory '/projects/myapp/myapp-war/src/main/resources', not found
Skipping task ':myapp-war:processResources' as it has no source files.
:myapp-war:processResources UP-TO-DATE
:myapp-war:processResources (Thread[Daemon worker Thread 4,5,main]) completed. Took 0.001 secs.
:myapp-war:classes (Thread[Daemon worker Thread 4,5,main]) started.
:myapp-war:classes
Skipping task ':myapp-war:classes' as it has no actions.
:myapp-war:classes UP-TO-DATE
:myapp-war:classes (Thread[Daemon worker Thread 4,5,main]) completed. Took 0.0 secs.
:myapp-war:gwtCompile (Thread[Daemon worker Thread 4,5,main]) started.
:myapp-war:gwtCompile
Executing task ':myapp-war:gwtCompile' (up-to-date check took 0.008 secs) due to:
  Input file /projects/myapp/myapp-war/build/classes/main/org/jboss/errai/cdi/EventQualifierSerializerImpl$2.class has changed.
  Input file /projects/myapp/myapp-war/build/classes/main/org/jboss/errai/cdi/EventQualifierSerializerImpl.class has changed.
  Input file /projects/myapp/myapp-war/build/classes/main/org/jboss/errai/cdi/EventQualifierSerializerImpl$5.class has changed.
```

As you can see, the **:myapp-war:compileJava** task knows that nothing changed, but the **:myapp-war:gwtCompile** task fails to detect that and launches unnecessary compilation every time I run **./gradlew compileGWT**

Any idea why? Is this something to do with special class files?

**Comment by fdumay** [comment]
I do not reproduce it on my projects.
What does the task compileGWT?

```
[ fdumay@mb-fabien ~/sources/putnami/putnami-gradle-plugin/samples/pgp-sample-webapp ] gradle gwtCompile
:compileJava
:processResources UP-TO-DATE
:gwtCompile
Compiling module fr.putnami.gradle.sample.webapp.App
   Compiling 5 permutations
      Compiling permutation 0...
      Compiling permutation 1...
      Compiling permutation 2...
      Compiling permutation 3...
      Compiling permutation 4...
   Compile of permutations succeeded
   Compilation succeeded -- 12,830s
Linking into /Users/fdumay/sources/putnami/putnami-gradle-plugin/samples/pgp-sample-webapp/build/putnami/out/App; Writing extras to /Users/fdumay/sources/putnami/putnami-gradle-plugin/samples/pgp-sample-webapp/build/putnami/extra/App
   Link succeeded
   Linking succeeded -- 0,218s

BUILD SUCCESSFUL

Total time: 15.388 secs
[ fdumay@mb-fabien ~/sources/putnami/putnami-gradle-plugin/samples/pgp-sample-webapp ] gradle gwtCompile
:compileJava UP-TO-DATE
:processResources UP-TO-DATE
:gwtCompile UP-TO-DATE

BUILD SUCCESSFUL

Total time: 0.697 secs
```

**Comment by hrstoyanov** [comment]
Let me get a clean demonstration of the issue or close it. Thanks.

**Comment by hrstoyanov** [comment]
@fdumay 
Well, I still see this issue... From the logs above, you can see I am using the Errai framework. I know it is using some kind of linkers and generators to produce those CDI proxy classes. I will ask in the Errai forum for ideas, but as you can see from the logs, whatever the Errai genarators **do it does not seem to confuse** ```compileJava``` **task as it correctly detects no change and skips**. It is only ```gwtCompile``` that gets tricked into thinking that those 3 classes changed? Further, after  the ```gwtCompile``` is run unnecessary, the ```war``` task is also tricked into repackaging the bundle:
```
Executing task ':myapp-war:war' (up-to-date check took 0.035 secs) due to:
  Input file /projects/myapp/myapp-war/build/classes/main/org/jboss/errai/cdi/EventQualifierSerializerImpl$2.class has changed.
  Input file /projects/myapp/myapp-war/build/classes/main/org/jboss/errai/cdi/EventQualifierSerializerImpl$3.class has changed.
  Input file /projects/myapp/myapp-war/build/putnami/out/myappApp/3C0CC7E96D24DC2DFE8264FAD0293A43.cache.js has been added.
```

**Comment by hrstoyanov** [comment]
@fdumay see this:
https://developer.jboss.org/message/958966#958966

**Comment by fdumay** [comment]
Well, if erai change some files, we need to recompile :/
Let me know!

**Comment by hrstoyanov** [comment]
Thanks @mbarkley
I saw your comment in the Errai forum:
https://developer.jboss.org/message/958966#958966
> Hi Hristo,
> The only suggestion I have is that it could be that the time stamps on some non-Java resources
> are changing between builds. For example, HTML files for templated beans are a resource that the Java compiler won't care about, but could trigger a new GWT compile since they will be included in
> a ClientBundle.

Unfortunately none of the input files (Java or HTML or others) are touched and yet issue is still present every time you launch the gradle build. 

I start to think that this is Errai generators issue for these reasons:
1. The standard Gradle WAR tasks also picks up the spurious change, it is not just this gradle gwt plug in.
2. In the generated directory, there are 5 total files created by Errai generators. But only the 3 shown above are causing the issue.
3. The problem occurs right after Java compilation (which detects no change according to the logs) and prior to Gwt compile, which already detect the spurious change. The only thing between the two is the Errai generation process. (Obviously there is no time in between for anyone to fiddle with he source files ...)

I will attach a complete log from the build, if you still need proof, but it sounds like something in Errai does not compare the right file timestamps...

**Comment by mbarkley** [comment]
@hrstoyanov Errai generators only run during a GWT compile. They can't cause a GWT compile to happen. Quite the opposite, GWT compilation is what causes the Errai generators to run.

**Comment by fdumay** [comment]
@hrstoyanov there no way that some thing changed from between the two builds?
The task defines that if anything change in the `src` folder, the list of the modules in the build.gradle or the output war folder, the task is not up to date.
Have you one task which could affect the war? 
I met the same kind of issue with the spring-boot-plugin, by default this one repackage the jar, so each time gradle needs to rebuild it.

**Comment by hrstoyanov** [comment]
@fdumay 
As you can see in the logs, Gradle does tell you which artifacts it thinks has changed and therefore it needs recompilation. And it is not just the "gwt compile", but also the standard "war" packaging task as well.  Remember, these happens during repeated runs of the ``gradle war``` command with no touching of any source files in between. I should attach the entire build run for you guys to see the exact sequence of task execution (later today)

@mbarkley 
Yes, the generators are part of the "umbrella" gwt compile task, but internally, they happen just prior to the JAVA->JS translation step,  (which is what I meant), right? These generators should be very careful with when a code generation is needed. 

I was previously thinking that this gwt plugin gets confused about inner classes (with $ in the name), but this does not appear to be the case (see the logs, there is a normal class in there), plus why only 3 out of the 5 Errai-generated files are the troublemakers, plus why the standard Gradle WAR task gets just as much confused?

.. Anyway, I do not have the debug level run logs right now. I will generate them later and we will hopefully have more information to reason about ... I will turn up the Errai codegen flags as well.

This is not a killer issue, but it is an irritating one, given how slow gwt compiles can be.

**Comment by hrstoyanov** [comment]
[forMaxAndFabien.txt](https://github.com/Putnami/putnami-gradle-plugin/files/329474/forMaxAndFabien.txt)

Ok please find attach the run log for the following command: ```gradlew -i war```.  With each run, **without changing any of the source files**, there will be an unnecessary gwt compilation and war packaging. If you look into the logs you will see Gradle complaining about 3 files being changed:

```
Executing task ':myapp-war:gwtCompile' (up-to-date check took 0.003 secs) due to:
  Input file /projects/myapp/myapp-war/build/classes/main/org/jboss/errai/cdi/EventQualifierSerializerImpl.class has changed.
  Input file /projects/myapp/myapp-war/build/classes/main/org/jboss/errai/cdi/EventQualifierSerializerImpl$5.class has changed.
  Input file /projects/myapp/myapp-war/build/classes/main/org/jboss/errai/cdi/EventQualifierSerializerImpl$3.class has changed.
```

Indeed, between two runs I noticed that they are re-generated (noticed the different timestamps) **for no apparent reason**:


After the 1st run
```
-rw-r--r-- 1 root root  882 Jun 23 08:02 /projects/myapp/myapp-war/build/classes/main/org/jboss/errai/cdi/EventQualifierSerializerImpl$1.class
-rw-r--r-- 1 root root  879 Jun 23 08:02 /projects/myapp/myapp-war/build/classes/main/org/jboss/errai/cdi/EventQualifierSerializerImpl$2.class
-rw-r--r-- 1 root root  901 Jun 23 08:02 /projects/myapp/myapp-war/build/classes/main/org/jboss/errai/cdi/EventQualifierSerializerImpl$3.class
-rw-r--r-- 1 root root  880 Jun 23 08:02 /projects/myapp/myapp-war/build/classes/main/org/jboss/errai/cdi/EventQualifierSerializerImpl$4.class
-rw-r--r-- 1 root root  860 Jun 23 08:02 /projects/myapp/myapp-war/build/classes/main/org/jboss/errai/cdi/EventQualifierSerializerImpl$5.class
-rw-r--r-- 1 root root 1737 Jun 23 08:02 /projects/myapp/myapp-war/build/classes/main/org/jboss/errai/cdi/EventQualifierSerializerImpl.class

```


After 2nd run, no source file changes of any kind:
```
-rw-r--r-- 1 root root  882 Jun 23 08:04 /projects/myapp/myapp-war/build/classes/main/org/jboss/errai/cdi/EventQualifierSerializerImpl$1.class
-rw-r--r-- 1 root root  879 Jun 23 08:04 /projects/myapp/myapp-war/build/classes/main/org/jboss/errai/cdi/EventQualifierSerializerImpl$2.class
-rw-r--r-- 1 root root  880 Jun 23 08:04 /projects/myapp/myapp-war/build/classes/main/org/jboss/errai/cdi/EventQualifierSerializerImpl$3.class
-rw-r--r-- 1 root root  901 Jun 23 08:04 /projects/myapp/myapp-war/build/classes/main/org/jboss/errai/cdi/EventQualifierSerializerImpl$4.class
-rw-r--r-- 1 root root  860 Jun 23 08:04 /projects/myapp/myapp-war/build/classes/main/org/jboss/errai/cdi/EventQualifierSerializerImpl$5.class
-rw-r--r-- 1 root root 1737 Jun 23 08:04 /projects/myapp/myapp-war/build/classes/main/org/jboss/errai/cdi/EventQualifierSerializerImpl.class
```
This makes me believe that this is a Errai 4 issue with the generators ...

**Comment by mbarkley** [comment]
@hrstoyanov I see now that it is *.class files generated by Errai that are the changed files. These files are in fact emitted by one of Errai's generators whenever it is run. We don't do caching between separate GWT compilations (except in SDM) so there is no way to avoid this.

A couple things you might try:

- I don't know Gradle, but can you have it ignore *.class files when checking for changed files before a GWT compilation? The GWT compiler doesn't use *.class files so there is no reason that a changed *.class file should trigger a GWT compile.

- This system property controls in which folder Errai emits the EventQualifierSerializerImpl class files: `errai.server.classOutput`. You could set it to a folder that isn't monitored for changes (but obviously you'll still need to package it in your war file).

**Comment by hrstoyanov** [comment]
@mbarkley , @fdumay 
Max, thanks for confirming the Errai behavior and the suggestions!
I was under the impression that Errai generators would do some file timestamp/checksum checks before emitting code. I do realize that effort involve witht his though ...

Fabien and I discussed in issue #47 that this plug in will need to work with its own Gradle configuration/classpath to avoid side effects. Maybe this is what I need to wait for before trying other things.

But as you see from the attached logs Gradle's standard WAR task also gets tricked into unnecessary repackaging  of the war bundle for the same reasons. I am curious how in Maven you avoid war repackaging - the maven WAR plug-in should have misfired the same way?

Anyway, let's wait for issue #47 in this plug-in, as this is not a killer issue for me.

**Comment by hrstoyanov** [comment]
This is an Errai issue, closing.

**Comment by hrstoyanov** [comment]
Btw, once you deploy and compile your app in SDM, you can skip additional GWT compilations for war changes like that:
```
gradlew war cargoRemoteRedeploy -x gwtCompile
```
where the deployment is done with the Cargo java plugin. ```-x gwtCompile``` will skip the unnecessary step and just proceed with war preparation and deployment
