### ISSUE TITLE
sourceLevel option question?

### ISSUE THREAD

**Issue by hrstoyanov** [Putnami/putnami-gradle-plugin#46]
According to the documentation, **sourceLevel** can be set in both ```dev{...}``` and ```compile{...}```. Can I, instead, set this option at the ```putnami{}``` level:
```
putnami{
  ...
  sourceLevel = '1.8'
}
```

**Comment by fdumay** [comment]
Enhancement accepted, We will be able to set the sourceLevel in putnami{}, then overrided in both compile and dev tasks

**Comment by hrstoyanov** [comment]
Thank you
