### ISSUE TITLE
Applying Mult-Project Build on Flat Structure

### ISSUE THREAD

**Issue by confile** [Putnami/putnami-gradle-plugin#7]
Your example https://github.com/Putnami/putnami-gradle-plugin/tree/master/samples/pgp-sample-multimodules has a hierarchical structure. I have a project with a flat structure.

My ``settings.gradle``looks like this: 

```
includeFlat "test-core"
```

This means that my directory structure looks like this: 
```
/
/test-core
/test-gwt
``` 

How do I apply your plugin for this structure of projects?

**Comment by fdumay** [comment]
I made a quick test and it work almost as the same way:

/test-core/build.gradle
```
buildscript {
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath 'fr.putnami.gwt:putnami-gradle-plugin:0.1.2'
	}
}

apply plugin: 'fr.putnami.gwt-lib'

repositories {
	mavenCentral()
}
```

/test-gwt/settings.gradle
```
includeFlat 'test-core'
project(":test-core").name = "test-core"
```

/test-gwt/build.gradle
```
buildscript {
	repositories {
		mavenCentral()
	}
	dependencies {
		classpath 'fr.putnami.gwt:putnami-gradle-plugin:0.1.2'
	}
}
apply plugin: 'fr.putnami.gwt'
repositories {
	mavenCentral()
}
dependencies{
	compile project(':test-core')
}
putnami{
	module '...'
}
```

**Comment by fdumay** [comment]
@confile are you okay with it? Please if you are please close that issue.

**Comment by confile** [comment]
yes. this issue is solved. Thank you so much.
